export const GUIDED_DEMO_STEPS = [
  {
    title: 'Project Objective',
    module: 'landing',
    description: 'The analysis examines whether selected market indicators are statistically associated with variation in observed daily stock returns.',
    targets: ['demo-objective', 'demo-variables'],
  },
  {
    title: 'Market Data',
    module: 'data',
    description: 'SYNTHETIC DEMO DATASET — This dataset is provided for demonstration only. Review its source, observation count, date range, variables, and computed preview.',
    targets: ['demo-data-summary', 'demo-data-source', 'demo-data-preview'],
  },
  {
    title: 'Data Preparation',
    module: 'data',
    description: 'The live processing log records validation, chronological ordering, return and volume-change calculations, lag creation, and rows removed when values cannot be calculated.',
    targets: ['demo-processing-log'],
    pipeline: [
      'Raw market data',
      'Validate required fields',
      'Order observations chronologically',
      'Calculate stock and market returns',
      'Calculate volume change',
      'Create previous-day return',
      'Remove non-calculable lag rows',
      'Analysis dataset',
    ],
  },
  {
    title: 'Descriptive Statistics',
    module: 'descriptive',
    description: 'Descriptive statistics help us understand the distribution and variation of the observed variables before modeling.',
    targets: ['demo-descriptive-stats', 'demo-histograms', 'demo-time-series'],
  },
  {
    title: 'Correlation',
    module: 'correlation',
    description: 'Pearson correlation measures the direction and strength of a linear association between numerical variables. Correlation does not establish causation.',
    targets: ['demo-correlation-pairs', 'demo-correlation-matrix', 'demo-scatter-plots'],
  },
  {
    title: 'Simple Regression',
    module: 'regression',
    description: 'The fitted equation is ŷ = β₀ + β₁x. The slope represents the fitted change in stock return associated with a one-unit increase in the selected predictor.',
    targets: ['demo-simple-equation', 'demo-simple-coefficients'],
    regressionTab: 'simple',
  },
  {
    title: 'Multiple Regression',
    module: 'regression',
    description: 'Multiple regression models the target using several predictors simultaneously. Coefficients describe associations while holding the other included predictors constant.',
    targets: ['demo-multiple-equation', 'demo-multiple-coefficients'],
    regressionTab: 'multiple',
  },
  {
    title: 'Model Evaluation',
    module: 'regression',
    description: 'The model is evaluated on later observations that were not used during training. MAE and RMSE measure error; R² describes variance explained, not accuracy.',
    targets: ['demo-model-evaluation', 'demo-actual-predicted'],
    regressionTab: 'multiple',
  },
  {
    title: 'Analysis Walkthrough Complete',
    module: 'landing',
    description: 'This application demonstrates a complete statistical workflow for analyzing stock returns using descriptive statistics, Pearson correlation, and regression.',
    targets: [],
  },
];
